name: for gitops
on:
  push:
    branches:
      - master
jobs:

  docker-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.image.outputs.version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      - name: Login to GitHub Packages Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            dlcksdnd6785/gitops:${{ steps.image.outputs.version }}
   
  update-manifest:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:    
      - name: Checkout kube-manifest repository
        uses: actions/checkout@v3
        with:
          repository: ChanWoongLee/kube-manifest
          token: ${{ secrets.ACTION_TOKEN }}
          ref: gitops

      - name : edit test
        run : |
          echo ${{ needs.docker-build-and-push.outputs.version }} >> text.txt
          
      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest

      - name: update yaml with yq
        run: |
          yq '(.spec.template.spec.containers.image | select(di == 1)) = "dlcksdnd6785/gitops:${{ steps.image.outputs.version }}" ' -i  gitops.yaml
          cat gitops.yaml

      - name: Commit andpush files
        run: |
          git config --global user.email "dlcksdnd6785@naver.com"
          git config --global user.name "ChanWoongLee"
          git add .
          git commit -am "update kube-manifest"
          git push -u origin gitops

  

    # - name: Update Kubernetes resources
    #   run: |
    #     cd example-app-kustomize/overlays/dev/
    #     kustomize edit set image ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}
    #     cat kustomization.yaml
    # - name: Commit files
    #   run: |
    #     cd example-app-kustomize
    #     git config --global user.email "github-actions@github.com"
    #     git config --global user.name "github-actions"
    #     git commit -am "Update image tag"
    #     git push -u origin main